version: '3'

services:
  sectest:
    image: raesene/sectest
    volumes:
      - data:/data
    ports:
      - "2222:22"
    networks:
      - testnet
  dradis:
    image: raesene/dradis
    ports:
      - "3000:3000"
    volumes:
      - data:/data
    networks:
      - testnet
volumes:
  data:
networks:
  testnet:
